providers = ["python"]

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "libGL", "libglib"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[start]
cmd = "gunicorn backend.main:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120"
